/**
 * Aegis Agent OS - Scenario Library & Plan Generator
 */

import { Task, ScenarioPreset, FinalDeliverable, MemoryItem } from '../types/agent';

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  {
    id: 'edtech_video_research',
    title: 'EdTech AI Video Platforms',
    category: 'Market & Product Research',
    objective:
      'Research the best AI tools for creating educational videos, compare them across pedagogical criteria, calculate ROI, verify findings, and prepare an executive recommendation.',
    description:
      'Full agentic lifecycle: Automated planning, tool-use, simulated tool failure & self-healing recovery, high-risk approval gate, and deep verification scorecard.',
    estimatedTasks: 9,
    recommendedAutonomy: 'balanced',
  },
  {
    id: 'enterprise_code_assistants',
    title: 'Enterprise AI Code Assistants',
    category: 'Technical Architecture & Security',
    objective:
      'Benchmark GitHub Copilot, Cursor, Codeium, and Claude Code for enterprise adoption, evaluating telemetry privacy, latency, SOC2 compliance, and developer velocity.',
    description:
      'Multi-agent technical evaluation with code interpreter sandbox, compliance database queries, and approval gate before final policy generation.',
    estimatedTasks: 8,
    recommendedAutonomy: 'supervised',
  },
  {
    id: 'cloud_finops_optimization',
    title: 'Cloud Infrastructure FinOps Plan',
    category: 'Operations & Financial Engineering',
    objective:
      'Audit multi-region Kubernetes clusters, identify orphaned block volumes and over-provisioned memory limits, and construct an automated rightsizing schedule.',
    description:
      'High-risk infrastructure scenario demonstrating safe approval barriers before scheduling compute restarts.',
    estimatedTasks: 7,
    recommendedAutonomy: 'supervised',
  },
];

/**
 * Baseline initial tasks for EdTech scenario
 */
export function getEdTechScenarioTasks(): Task[] {
  return [
    {
      id: 'task-01',
      order: 1,
      title: 'Deconstruct Objective & Constraint Parameters',
      description: 'Analyze user intent, extract core criteria (student engagement, accessibility, pricing, licensing), and define success criteria.',
      assignedAgent: 'supervisor',
      requiredTool: 'knowledge_base',
      riskLevel: 'low',
      priority: 'high',
      dependencies: [],
      estimatedDuration: '1.2s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: 'Initialize supervisor intake with pedagogical taxonomy standards',
        why: 'Defining explicit constraints prevents hallucinated scope creep during subsequent tool execution.',
        evidence: 'Goal specifies educational video creation, requiring FERPA, WCAG transcription, and cost viability.',
        confidence: 'high',
        confidenceScore: 97,
        nextAction: 'Hand off formalized criteria schema to Planning Agent.',
        factors: ['Clear scope bounds', 'Established Bloom taxonomy reference', 'Deterministic user prompt'],
      },
    },
    {
      id: 'task-02',
      order: 2,
      title: 'Construct Dependency-Aware Execution Plan',
      description: 'Generate topological task graph, assign specialized agents, configure approval checkpoints, and set verification thresholds.',
      assignedAgent: 'planner',
      requiredTool: 'code_interpreter',
      riskLevel: 'low',
      priority: 'high',
      dependencies: ['task-01'],
      estimatedDuration: '1.5s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: 'Sequence research before analysis, insert Approval Gate at publication phase',
        why: 'Analysis requires empirical tool outputs; external sharing requires human governance check.',
        evidence: 'Risk model dictates external publication is Medium-High risk under Enterprise Policy #14.',
        confidence: 'high',
        confidenceScore: 95,
        nextAction: 'Dispatch Research Agent to query current web index.',
        factors: ['Strict dependency graph', 'Zero circular dependencies', 'Pre-configured recovery routes'],
      },
    },
    {
      id: 'task-03',
      order: 3,
      title: 'Query Live Web Index for Top EdTech Platforms',
      description: 'Execute targeted web search queries to identify current market leaders in AI avatar instruction and synthetic voice synthesis.',
      assignedAgent: 'researcher',
      requiredTool: 'web_search',
      riskLevel: 'medium',
      priority: 'high',
      dependencies: ['task-02'],
      estimatedDuration: '2.4s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: 'Execute multi-keyword search across academic & enterprise software repositories',
        why: 'Live market offerings for generative video have evolved rapidly between 2024 and 2026.',
        evidence: 'Recent breakthroughs in low-latency avatar lip-sync require real-time index verification.',
        confidence: 'high',
        confidenceScore: 91,
        nextAction: 'Extract candidate vendor pool (Synthesia, HeyGen, Colossyan, Elai).',
        factors: ['Multi-source index breadth', 'Recency filtering (2025-2026)', 'Peer-reviewed pedagogical papers'],
      },
    },
    {
      id: 'task-04',
      order: 4,
      title: 'Verify Student Privacy & WCAG 2.2 Compliance Standards',
      description: 'Cross-reference candidate tools against FERPA, COPPA, automated subtitle accuracy, and multi-lingual voice naturalness.',
      assignedAgent: 'researcher',
      requiredTool: 'knowledge_base',
      riskLevel: 'low',
      priority: 'medium',
      dependencies: ['task-03'],
      estimatedDuration: '1.8s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: 'Cross-reference vendor data retention policies against institutional privacy catalog',
        why: 'Educational deployments require strict zero-training clauses on student and faculty likenesses.',
        evidence: 'Institutional Security Directive v3.8 mandates SOC2 Type II + explicit FERPA addendum.',
        confidence: 'high',
        confidenceScore: 94,
        nextAction: 'Forward filtered vendor list to Analysis Agent for multi-criteria matrix scoring.',
        factors: ['Authoritative compliance catalog', 'Legally binding terms analysis', 'Accessibility standards'],
      },
    },
    {
      id: 'task-05',
      order: 5,
      title: 'Multi-Criteria Feature & Pedagogical Matrix Analysis',
      description: 'Normalize evaluation scores across avatar realism, quiz integration, LMS export (SCORM/xAPI), and generation speed.',
      assignedAgent: 'analyst',
      requiredTool: 'data_analyzer',
      riskLevel: 'low',
      priority: 'high',
      dependencies: ['task-04'],
      estimatedDuration: '2.0s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: 'Apply weighted multi-attribute decision model (MADM) across 18 criteria',
        why: 'Raw features alone do not reflect real classroom learning retention or instructional design speed.',
        evidence: 'Pedagogical research shows interactive check-ins produce 2.3x higher knowledge retention than passive video.',
        confidence: 'high',
        confidenceScore: 93,
        nextAction: 'Hand off scoring vectors to Executor for financial modeling.',
        factors: ['18 evaluated vectors', 'Statistical normalization applied', 'Zero arbitrary point inflation'],
      },
    },
    {
      id: 'task-06',
      order: 6,
      title: 'Calculate Financial ROI, TCO, and Production Unit Economics',
      description: 'Model costs comparing traditional video production (studio, filming, voiceover) versus automated AI video workflows.',
      assignedAgent: 'executor',
      requiredTool: 'calculator',
      riskLevel: 'low',
      priority: 'medium',
      dependencies: ['task-05'],
      estimatedDuration: '1.4s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: 'Calculate baseline 50-course production cost model with 3.8-month payback horizon',
        why: 'Institutional leadership requires defensible capital justification prior to software license approval.',
        evidence: 'Traditional studio cost averages $3,360/course vs. $850/course using modern AI synthetic pipelines.',
        confidence: 'high',
        confidenceScore: 96,
        nextAction: 'Raise Human Approval Gate before compiling and publishing executive recommendation.',
        factors: ['Deterministic cost equations', 'Conservative revision allowances', 'Vendor enterprise tier pricing'],
      },
    },
    {
      id: 'task-07',
      order: 7,
      title: 'Human-in-the-Loop Governance Checkpoint: Approve Executive Strategy',
      description: 'Pause execution to obtain explicit human sign-off on the top vendor recommendation and financial allocation model.',
      assignedAgent: 'supervisor',
      requiredTool: 'document_generator',
      riskLevel: 'high',
      priority: 'critical',
      dependencies: ['task-06'],
      estimatedDuration: 'Human input',
      status: 'pending',
      progress: 0,
      approval: {
        required: true,
        riskLevel: 'high',
        status: 'pending',
        reason: 'Final recommendation commits institutional strategy and selects preferred commercial procurement vendor.',
        requestedAction: 'Approve recommendation of Synthesia & Colossyan enterprise pilots and authorization of draft synthesis.',
        consequences: 'Authorizes agent to assemble final publishable executive report and sign off verification scores.',
      },
      reasoningSummary: {
        decision: 'Hold execution pipeline at Tier 3 Human Approval Barrier',
        why: 'Ethical governance mandates human agency over enterprise budget recommendations and vendor selection.',
        evidence: 'System Policy #02: Any procurement ranking influencing >$25k budget requires explicit human confirmation.',
        confidence: 'moderate',
        confidenceScore: 88,
        nextAction: 'Await operator click: Approve, Reject, or Modify Plan.',
        factors: ['Human accountability requirement', 'Financial threshold triggered', 'Governance protocol compliance'],
      },
    },
    {
      id: 'task-08',
      order: 8,
      title: 'Rigorous Verification Engine & Factual Quality Audit',
      description: 'Audit report draft against accuracy, completeness, relevance, and consistency rubrics before final sign-off.',
      assignedAgent: 'verifier',
      requiredTool: 'code_interpreter',
      riskLevel: 'low',
      priority: 'high',
      dependencies: ['task-07'],
      estimatedDuration: '1.6s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: 'Audit factual consistency across 24 citations and verify mathematical balance of ROI projections',
        why: 'Preventing subtle hallucinations or unit discrepancies ensures the deliverable is boardroom-ready.',
        evidence: 'Verification score calculated at 94.2% across accuracy, completeness, and pedagogical relevance.',
        confidence: 'high',
        confidenceScore: 98,
        nextAction: 'Emit verified quality seal and deliver final interactive document.',
        factors: ['Multi-agent cross-check', 'Citation provenance verified', 'Zero contradictory claims'],
      },
    },
    {
      id: 'task-09',
      order: 9,
      title: 'Synthesize Boardroom-Ready Executive Deliverable',
      description: 'Compile final formatted report with executive summary, benchmark table, ROI breakdown, and direct procurement next steps.',
      assignedAgent: 'supervisor',
      requiredTool: 'document_generator',
      riskLevel: 'low',
      priority: 'high',
      dependencies: ['task-08'],
      estimatedDuration: '1.5s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: 'Render comprehensive final deliverable with dual export and audit log verification',
        why: 'Delivers immediate real-world utility in a clean, executive-grade structure.',
        evidence: 'All 8 preceding tasks completed and verified with human approval signature recorded.',
        confidence: 'high',
        confidenceScore: 99,
        nextAction: 'Notify user of completed objective and archive execution run into immutable audit trail.',
        factors: ['Complete objective fulfillment', 'High verification score (94%)', 'Full audit trail preserved'],
      },
    },
  ];
}

/**
 * Generate a dynamic structured plan for ANY user entered goal
 */
export function generateDynamicPlan(goalText: string): Task[] {
  const cleanGoal = goalText.trim();
  const isSecurity = /security|vulnerability|audit|cve|incident|breach/i.test(cleanGoal);
  const isFinance = /cost|finops|budget|financial|spend|pricing|roi/i.test(cleanGoal);
  const isCoding = /code|software|api|github|deploy|kubernetes|database/i.test(cleanGoal);

  return [
    {
      id: 'task-dyn-01',
      order: 1,
      title: `Deconstruct Objective: "${cleanGoal.slice(0, 48)}${cleanGoal.length > 48 ? '...' : ''}"`,
      description: `Analyze scope boundaries, target audience, constraint parameters, and deliverables for: "${cleanGoal}".`,
      assignedAgent: 'supervisor',
      requiredTool: 'knowledge_base',
      riskLevel: 'low',
      priority: 'high',
      dependencies: [],
      estimatedDuration: '1.2s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: 'Map high-level goal into structured schema of constraints and success metrics',
        why: 'Clear parameterization ensures all down-stream specialized agents operate with unambiguous criteria.',
        evidence: `Extracted intent vectors: Domain=${isSecurity ? 'Cybersecurity' : isFinance ? 'Finance/FinOps' : isCoding ? 'Software/Cloud' : 'Research & Analysis'}, Output=Actionable Executive Deliverable.`,
        confidence: 'high',
        confidenceScore: 96,
        nextAction: 'Instruct Planning Agent to construct topological task graph.',
        factors: ['Semantic intent deconstruction', 'Safety constraint bounding', 'Deliverable specification'],
      },
    },
    {
      id: 'task-dyn-02',
      order: 2,
      title: 'Synthesize Multi-Stage Execution Plan & Risk Gates',
      description: 'Formulate dependency-aware task graph, allocate specialized agents, and calibrate approval gates.',
      assignedAgent: 'planner',
      requiredTool: 'code_interpreter',
      riskLevel: 'low',
      priority: 'high',
      dependencies: ['task-dyn-01'],
      estimatedDuration: '1.4s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: 'Sequence tasks with parallel research branches and insert mandatory Human Approval Gate before final output',
        why: 'Guarantees execution safety and prevents uncontrolled downstream actions.',
        evidence: 'Risk classifier calculated risk profile and assigned appropriate human oversight checkpoints.',
        confidence: 'high',
        confidenceScore: 94,
        nextAction: 'Dispatch Research Agent with target queries.',
        factors: ['Topological sequencing', 'Approval gate placement', 'Tool dependency mapping'],
      },
    },
    {
      id: 'task-dyn-03',
      order: 3,
      title: 'Execute Targeted Information Gathering & Evidence Discovery',
      description: 'Query external sources, documentation repositories, and market benchmarks relevant to the objective.',
      assignedAgent: 'researcher',
      requiredTool: isSecurity ? 'database_query' : 'web_search',
      riskLevel: 'medium',
      priority: 'high',
      dependencies: ['task-dyn-02'],
      estimatedDuration: '2.2s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: `Query primary indexes for domain-grounded evidence on ${cleanGoal.slice(0, 36)}`,
        why: 'Empirical data collection ensures findings are based on current, authoritative facts.',
        evidence: 'Discovered high-relevance sources ready for filtering and normalization.',
        confidence: 'high',
        confidenceScore: 92,
        nextAction: 'Filter raw hits against credibility rubrics.',
        factors: ['Index recency', 'Citation count', 'Domain authority'],
      },
    },
    {
      id: 'task-dyn-04',
      order: 4,
      title: 'In-Depth Analysis & Comparative Modeling',
      description: 'Process collected data points, synthesize trade-offs, compute metrics, and establish core findings.',
      assignedAgent: 'analyst',
      requiredTool: 'data_analyzer',
      riskLevel: 'low',
      priority: 'high',
      dependencies: ['task-dyn-03'],
      estimatedDuration: '1.9s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: 'Apply multi-variate analysis to evaluate trade-offs and calculate objective scores',
        why: 'Raw search snippets require structured synthesis to yield actionable strategic insight.',
        evidence: 'Correlation analysis identified top 3 primary leverage points.',
        confidence: 'high',
        confidenceScore: 93,
        nextAction: 'Formulate concrete strategic recommendations.',
        factors: ['Multi-variate normalization', 'Outlier elimination', 'Deterministic rubric weights'],
      },
    },
    {
      id: 'task-dyn-05',
      order: 5,
      title: 'Human-in-the-Loop Approval Gate: Authorize Strategy Proposal',
      description: 'Present synthesized strategy and trade-off options for explicit human review and sign-off.',
      assignedAgent: 'supervisor',
      requiredTool: 'document_generator',
      riskLevel: 'high',
      priority: 'critical',
      dependencies: ['task-dyn-04'],
      estimatedDuration: 'Human input',
      status: 'pending',
      progress: 0,
      approval: {
        required: true,
        riskLevel: 'high',
        status: 'pending',
        reason: `Proposed strategy for "${cleanGoal.slice(0, 40)}" commits operational direction.`,
        requestedAction: 'Authorize execution of verified final deliverable compilation.',
        consequences: 'Agent will proceed to verification phase and generate immutable audit log entries.',
      },
      reasoningSummary: {
        decision: 'Pause pipeline at Tier 3 Human Approval Barrier',
        why: 'High-impact strategic actions require explicit human affirmation per System Safety Protocol.',
        evidence: 'High confidence score achieved (91%), but policy requires human sign-off on strategy.',
        confidence: 'moderate',
        confidenceScore: 89,
        nextAction: 'Await operator confirmation in UI.',
        factors: ['Human accountability requirement', 'Safety protocol #01', 'Operational impact'],
      },
    },
    {
      id: 'task-dyn-06',
      order: 6,
      title: 'Autonomous Verification & Quality Audit',
      description: 'Examine factual coherence, citation validity, internal consistency, and metric integrity.',
      assignedAgent: 'verifier',
      requiredTool: 'code_interpreter',
      riskLevel: 'low',
      priority: 'high',
      dependencies: ['task-dyn-05'],
      estimatedDuration: '1.6s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: 'Perform automated 4-vector verification (Accuracy, Completeness, Relevance, Consistency)',
        why: 'Guarantees the final output is free of logical leaps, hallucinations, or unverified claims.',
        evidence: 'All metrics evaluated above the minimum 85% verification threshold.',
        confidence: 'high',
        confidenceScore: 96,
        nextAction: 'Issue cryptographic verification seal and compile final deliverable.',
        factors: ['4-vector rubric check', 'Evidence-to-claim alignment', 'Zero contradiction verified'],
      },
    },
    {
      id: 'task-dyn-07',
      order: 7,
      title: 'Compile & Format Final Deliverable',
      description: 'Generate polished final deliverable complete with executive overview, matrix, and next actions.',
      assignedAgent: 'supervisor',
      requiredTool: 'document_generator',
      riskLevel: 'low',
      priority: 'high',
      dependencies: ['task-dyn-06'],
      estimatedDuration: '1.3s',
      status: 'pending',
      progress: 0,
      reasoningSummary: {
        decision: 'Deliver executive report with complete audit metadata and export formats',
        why: 'Satisfies the user objective in an immediately actionable format.',
        evidence: '100% of planned tasks executed with verified human approval recorded.',
        confidence: 'high',
        confidenceScore: 99,
        nextAction: 'Transition agent state to COMPLETED and unlock export options.',
        factors: ['Full objective fulfillment', 'Comprehensive citation map', 'Audit trail finalized'],
      },
    },
  ];
}

/**
 * Pre-compiled rich deliverable for the EdTech demo
 */
export function getEdTechDeliverable(totalSeconds: number): FinalDeliverable {
  return {
    objective:
      'Research the best AI tools for creating educational videos, compare them across pedagogical criteria, calculate ROI, verify findings, and prepare an executive recommendation.',
    executiveSummary:
      'Generative AI video platforms have transitioned from novelty avatar demonstrations into enterprise-grade pedagogical assets. For institutions producing modular e-learning, micro-credentials, and faculty training, our evaluation identifies Synthesia and Colossyan as market leaders. Deploying an AI video creation workflow achieves an estimated 74.7% reduction in course asset production costs, accelerates time-to-publish from 4.2 weeks to 3.5 business days, and ensures full WCAG 2.2 AA accessibility compliance via automated multi-lingual closed captions.',
    keyFindings: [
      'Production Cost Efficiency: Traditional studio production of a 10-module course costs $33,600 on average. AI synthetic video workflows reduce this to $8,500, delivering a 295% net ROI in year one.',
      'Pedagogical Engagement: Interactive scenario-branching (supported natively by Colossyan) yielded 2.3x higher test retention compared to static talking-head lectures.',
      'Accessibility & Compliance: HeyGen and Synthesia lead in real-time lip-synced localization across 80+ languages, fulfilling Section 508 and WCAG 2.2 AA requirements with zero human translation latency.',
      'Data Privacy & Likeness Rights: Only Synthesia and Colossyan provide contractually binding FERPA and SOC2 Type II addendums guaranteeing zero-training on faculty avatar recordings.',
    ],
    recommendations: [
      {
        title: 'Adopt Synthesia for Enterprise-Wide Lecture & Knowledge Base Updates',
        priority: 'Immediate',
        effort: 'Low',
        description:
          'Roll out Synthesia Enterprise across the Center for Teaching Excellence to update outdated static course slide decks into dynamic micro-lessons.',
        impact: 'Saves 380+ hours of studio booking time within the first academic quarter.',
      },
      {
        title: 'Pilot Colossyan for Clinical & Scenario-Based Branching Modules',
        priority: 'Strategic',
        effort: 'Medium',
        description:
          'Utilize Colossyan’s in-video multiple-choice quizzes and multi-avatar conversations for compliance and medical simulation coursework.',
        impact: 'Raises course completion rate by an estimated +34% based on pilot metrics.',
      },
      {
        title: 'Establish Institutional Likeness & AI Voice Governance Policy',
        priority: 'Immediate',
        effort: 'Low',
        description:
          'Codify written faculty consent requirements before creating custom photorealistic avatars or synthetic voice clones.',
        impact: 'Prevents legal liability and builds trusted faculty adoption.',
      },
      {
        title: 'Integrate SCORM / xAPI Export with Canvas & Blackboard LMS',
        priority: 'Optional',
        effort: 'Medium',
        description:
          'Enable direct cloud webhook pipeline from video generation studio directly into institutional LMS course catalogs.',
        impact: 'Eliminates manual file downloading, re-encoding, and server storage sprawl.',
      },
    ],
    comparisons: {
      headers: ['Platform', 'Core Focus', 'Pedagogical Score', 'Key Strengths', 'Key Limitations', 'Enterprise Pricing'],
      rows: [
        {
          item: 'Synthesia Enterprise',
          category: 'Enterprise Scale',
          score: '96 / 100',
          pros: '160+ photorealistic avatars, SOC2 Type II, FERPA compliant, seamless multi-lingual translation',
          cons: 'Advanced branching quizzes require external LMS authoring tool',
          pricing: '$89/user/month (Tiered Enterprise)',
        },
        {
          item: 'Colossyan Creator',
          category: 'Interactive Learning',
          score: '93 / 100',
          pros: 'Native multiple-choice quiz interactions, multiple avatars on screen, SCORM/xAPI direct export',
          cons: 'Fewer total avatar wardrobe variations than Synthesia',
          pricing: '$72/user/month (Education Discount)',
        },
        {
          item: 'HeyGen Video',
          category: 'Hyper-Realistic Voice',
          score: '89 / 100',
          pros: 'Industry-leading audio voice cloning and expressive emotive inflections, fast rendering',
          cons: 'Enterprise security documentation requires custom procurement negotiation',
          pricing: '$80/month (Team Plan)',
        },
        {
          item: 'Elai.io',
          category: 'Automated Curriculum',
          score: '84 / 100',
          pros: 'Direct URL / PDF-to-video conversion, gamified avatar templates',
          cons: 'Occasional lip-sync latency on complex academic jargon',
          pricing: '$59/month (Basic Business)',
        },
      ],
    },
    sources: [
      {
        name: 'Global EdTech Pedagogical Index 2026',
        url: 'https://research.edtech-global.org/reports/ai-video-2026',
        reliability: 'Tier 1 Academic/Gov',
        date: 'January 2026',
      },
      {
        name: 'Higher Education Video Retention & Cognitive Load Study',
        url: 'https://hstar.stanford.edu/publications/synthetic-pedagogy',
        reliability: 'Tier 1 Academic/Gov',
        date: 'November 2025',
      },
      {
        name: 'Gartner Hype Cycle for K-20 Education Technology',
        url: 'https://gartner.com/en/documents/edtech-synthetic-media',
        reliability: 'Verified Industry Report',
        date: 'December 2025',
      },
      {
        name: 'SOC2 Security & FERPA Architecture Documentation',
        url: 'https://trust.synthesia.io/compliance-ferpa-matrix',
        reliability: 'Direct Vendor Spec',
        date: 'February 2026',
      },
    ],
    verificationScorecard: {
      accuracy: 96,
      completeness: 95,
      relevance: 98,
      consistency: 94,
      quality: 96,
      overall: 96,
      feedback:
        'All 4 evaluated platforms benchmarked against verified 2026 pricing, FERPA compliance, and WCAG accessibility standards. Mathematical financial modeling balanced with deterministic formulas. Human approval verified.',
      passed: true,
      verifiedAt: new Date().toLocaleTimeString(),
    },
    executionStats: {
      totalDurationSeconds: totalSeconds,
      tasksTotal: 9,
      tasksCompleted: 9,
      toolsInvoked: 8,
      approvalsRequested: 1,
      approvalsGranted: 1,
      recoveriesAttempted: 1,
    },
  };
}

/**
 * Initial Agent Memory Seeds
 */
export const INITIAL_MEMORIES: MemoryItem[] = [
  {
    id: 'mem-01',
    type: 'long_term',
    content: 'Enterprise Safety Rule #01: External publications and vendor selections exceeding $25,000 mandate explicit human approval.',
    source: 'Corporate Governance Policy v4.2',
    timestamp: '2026-09-15 08:00',
    confidence: 100,
    relevance: 98,
  },
  {
    id: 'mem-02',
    type: 'long_term',
    content: 'Accessibility Mandate: All synthesized instructional media must include synchronized WebVTT subtitles meeting WCAG 2.2 AA standards.',
    source: 'Digital Accessibility Office',
    timestamp: '2026-09-20 10:30',
    confidence: 100,
    relevance: 95,
  },
  {
    id: 'mem-03',
    type: 'working',
    content: 'Identified 4 qualified video platforms: Synthesia, Colossyan, HeyGen, Elai. Filtered out unverified beta tools.',
    source: 'Research Agent / Task 03',
    timestamp: 'Current Session',
    confidence: 94,
    relevance: 96,
  },
  {
    id: 'mem-04',
    type: 'short_term',
    content: 'Active objective: Educational video platforms research and executive recommendation generation.',
    source: 'Supervisor Intake',
    timestamp: 'Current Session',
    confidence: 99,
    relevance: 100,
  },
];
